### ISSUE TITLE
Top graph - Update colours on points/ranges for provinces, '1.0' line, text, and all lines in graph.

### ISSUE THREAD

**Issue by martinlaws** [consultlowtide/rt-canada#15]
Ryan to add the colours and hex codes here

**Comment by ryan-neufeld** [comment]
Lines - #D8D8D8
Line Labels - #777677
1.0 Line - #DE372D
Semi Circle Border - #40CC7E (Green) and #ED6453 (Red)
Semi Circle Text - #3CB66C (Green) and #E64F40 (Red)
Confidence Interval Ranges - #C7F5C0 (Green) and #FFDAD2 (Red)

**Comment by martinlaws** [comment]
Re: 1.0 line: https://github.com/consultlowtide/rt-canada/issues/24#issuecomment-635057731
