### ISSUE TITLE
Area Graphs - Change points/dots to a line. Either remove dots or make them smaller, let's feel it out.

### ISSUE THREAD

**Issue by ryan-neufeld** [consultlowtide/rt-canada#19]
* Line Colour: 
  * Red: #DE372D
  * Green: #3FC156
* Line Width: 1.5px (round up to 2px if half pixels are no good)
* Remove dots
<img width="643" alt="Screen Shot 2020-05-21 at 11 44 07 PM" src="https://user-images.githubusercontent.com/49967887/82629205-0009fc00-9bbd-11ea-9140-8a69d6e2260c.png">

**Comment by martinlaws** [comment]
@ryan-neufeld this is trickier than I expected, here are two totally doable options:
1) keep dots, make them smaller, any > 1 are red, any < 1 are green
2) switch to a line, all one colour

Let me know your preference 🙏

**Comment by ryan-neufeld** [comment]
Hmmmm @martinlaws is it possible to see what both would look like first? I'm partial to a line if we're not able to shorten the time horizon we're visualizing but  I kinda want to see the circles first if that's possible.
