### ISSUE TITLE
Top  graph - '1' Horizontal Line - Make it #DE372D

### ISSUE THREAD

**Issue by ryan-neufeld** [consultlowtide/rt-canada#24]

**Comment by martinlaws** [comment]
yo @ryan-neufeld either I'm going crazy, or the #DE372D is bright red. The "1" Horizontal Line in Abstract is grey - what say you?

**Comment by ryan-neufeld** [comment]
> yo @ryan-neufeld either I'm going crazy, or the #DE372D is bright red. The "1" Horizontal Line in Abstract is grey - what say you?

Red. Let me check the Abstract link, it might be out of date.
