### ISSUE TITLE
Update Font families - Add IBM Plex Sans (body) and Inknut Antiqua (headlines) to the page.

### ISSUE THREAD

**Issue by ryan-neufeld** [consultlowtide/rt-canada#27]
<img width="1126" alt="Screen Shot 2020-05-24 at 4 00 11 PM" src="https://user-images.githubusercontent.com/49967887/82763728-bb0de180-9dd7-11ea-8d4a-60662c4f6bf1.png">

**Comment by martinlaws** [comment]
@ryan-neufeld we'll need to rework these typography styles to match material UI for now - here are the 13 font variants available to us: https://material-ui.com/components/typography/#component

**Comment by ryan-neufeld** [comment]
@martinlaws I don't understand what you mean exactly. Like do you just mean the naming convention? Or do you need me to provide 13 variants or?
