### ISSUE TITLE
Change page margins - We want to the content to take up more of the screen on wider displays (like a 15" macbook so people can easily read the graphs) Not sure if this is % based or what. See designs for suggestions based on 1280 width but let's talk.

### ISSUE THREAD

**Issue by ryan-neufeld** [consultlowtide/rt-canada#28]
@martinlaws I can't remember what you said the solution was here but I know you said rt.live is using a non-standard width. My designs are done on a 1280 width artboard with a 48px left and right margin so let me know if there's anything I can do to help clarify better here.

**Comment by martinlaws** [comment]
The current container does max out at 1280 width:
<img width="1680" alt="Screen Shot 2020-05-27 at 10 59 58 PM" src="https://user-images.githubusercontent.com/13721239/83093693-e7db2680-a06d-11ea-80a6-5a09d48369c5.png">
