### ISSUE TITLE
Top graph - Restyle Popover - Move Rt # to the right of the province name, update text styles/font family and colours, add colour coding of Rt value/ranges, remove border and add shadow. See Abstract Inspect for details.

### ISSUE THREAD

**Issue by ryan-neufeld** [consultlowtide/rt-canada#31]
<img width="588" alt="Screen Shot 2020-05-24 at 4 25 13 PM" src="https://user-images.githubusercontent.com/49967887/82764217-31601300-9ddb-11ea-8032-b1a2bed50415.png">

**Province**
Text: Subtitle - IBM Plex Sans - SemiBold - 14
Colours: #000000

**Rt**
Text: Subtitle - IBM Plex Sans - SemiBold - 14
Colours: #3CB66C (Green), #E64F40 (Red)

**High/Low**
Text: Caption - IBM Plex Sans - Regular - 12
Colour: #777677 (Grey)

**Rt High/Low**
Text: Caption - IBM Plex Sans - Regular - 12
Colours: #3CB66C (Green for less than 1), #E64F40 (Red for 1 or more)

**Container**
Padding: 16px padding
No border
Corner Radius: 4
Shadows: Not sure how to communicate this, will attach a screenshot.

<img width="248" alt="Screen Shot 2020-05-24 at 4 37 15 PM" src="https://user-images.githubusercontent.com/49967887/82764471-d9c2a700-9ddc-11ea-98a6-782e624faa72.png">

**Comment by martinlaws** [comment]
Closing this issue as it appears to have been addressed in #35
